-- Initial migration: Create all tables from unified schema
-- Generated by prisma migrate diff --from-empty --to-schema

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "NotificationType" AS ENUM ('TRANSACTION', 'SECURITY', 'MARKETING', 'PRICE_ALERT', 'SYSTEM', 'OTP');

-- CreateEnum
CREATE TYPE "TransactionType" AS ENUM ('ON_RAMP', 'OFF_RAMP');

-- CreateEnum
CREATE TYPE "TransactionStatus" AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', 'EXPIRED');

-- CreateEnum
CREATE TYPE "ComplianceStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'UNDER_REVIEW');

-- CreateEnum
CREATE TYPE "KycStatus" AS ENUM ('PENDING', 'VERIFIED', 'REJECTED', 'EXPIRED');

-- CreateEnum
CREATE TYPE "FeeType" AS ENUM ('PLATFORM_FEE', 'PROVIDER_FEE', 'NETWORK_FEE', 'EXCHANGE_FEE');

-- CreateEnum
CREATE TYPE "WebhookStatus" AS ENUM ('PENDING', 'DELIVERED', 'FAILED', 'EXPIRED');

-- CreateEnum
CREATE TYPE "PaymentMethod" AS ENUM ('USSD_PUSH', 'OTP_PAYMENT', 'WEB_REDIRECT', 'QR_CODE', 'DIRECT_DEBIT');

-- CreateEnum
CREATE TYPE "IdempotencyStatus" AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED');

-- CreateEnum
CREATE TYPE "QueueJobStatus" AS ENUM ('PENDING', 'ACTIVE', 'COMPLETED', 'FAILED', 'DELAYED', 'RETRYING');

-- CreateEnum
CREATE TYPE "DeFiBundleStatus" AS ENUM ('PENDING', 'CONFIRMED', 'FAILED', 'PARTIALLY_EXECUTED');

-- CreateEnum
CREATE TYPE "LedgerEntryType" AS ENUM ('ON_RAMP_CREDIT', 'OFF_RAMP_DEBIT', 'OFF_RAMP_REFUND', 'FEE_COLLECTION', 'TREASURY_DEPOSIT', 'TREASURY_WITHDRAWAL');

-- CreateEnum
CREATE TYPE "LedgerEntryStatus" AS ENUM ('PENDING', 'SUBMITTED', 'CONFIRMED', 'FAILED', 'REVERTED');

-- CreateEnum
CREATE TYPE "CommissionType" AS ENUM ('FIAT_ONRAMP', 'FIAT_OFFRAMP', 'DEFI_LENDING', 'SUPPLY_COMMISSION', 'BORROW_COMMISSION', 'LIQUIDATION_COMMISSION', 'YIELD_COMMISSION', 'VAULT_MANAGEMENT_FEE', 'VAULT_PERFORMANCE_FEE');

-- CreateEnum
CREATE TYPE "MorphoTransactionType" AS ENUM ('SUPPLY', 'WITHDRAW', 'BORROW', 'REPAY', 'LIQUIDATE', 'SUPPLY_COLLATERAL', 'WITHDRAW_COLLATERAL', 'VAULT_DEPOSIT', 'VAULT_WITHDRAW');

-- CreateEnum
CREATE TYPE "MorphoTransactionStatus" AS ENUM ('PENDING', 'CONFIRMED', 'FAILED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "MissionStatus" AS ENUM ('PENDING', 'DEPOSITING', 'APPROVING', 'ACTIVE', 'PAUSED', 'COMPLETING', 'COMPLETED', 'LIQUIDATED', 'REVOKED');

-- CreateEnum
CREATE TYPE "StrategyType" AS ENUM ('SHORT_TERM_30D', 'LONG_TERM_45D', 'CUSTOM');

-- CreateEnum
CREATE TYPE "AgentRiskLevel" AS ENUM ('CONSERVATIVE', 'MODERATE', 'AGGRESSIVE');

-- CreateEnum
CREATE TYPE "TradeDirection" AS ENUM ('LONG', 'SHORT');

-- CreateEnum
CREATE TYPE "ConfidenceLevel" AS ENUM ('LOW', 'MEDIUM', 'HIGH');

-- CreateEnum
CREATE TYPE "PositionStatus" AS ENUM ('OPEN', 'CLOSED', 'LIQUIDATED');

-- CreateTable
CREATE TABLE "users" (
    "id" TEXT NOT NULL,
    "phoneNumber" TEXT NOT NULL,
    "isVerified" BOOLEAN NOT NULL DEFAULT false,
    "firstName" TEXT,
    "lastName" TEXT,
    "email" TEXT,
    "walletAddress" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "address" TEXT,
    "city" TEXT,
    "country" TEXT,
    "dateOfBirth" TIMESTAMP(3),
    "gender" TEXT,
    "idNumber" TEXT,
    "idType" TEXT,
    "kycData" JSONB,
    "kycStatus" TEXT NOT NULL DEFAULT 'PENDING',
    "monthlyIncome" TEXT,
    "nationality" TEXT,
    "occupation" TEXT,
    "turnkeySubOrgId" TEXT,
    "turnkeyUserId" TEXT,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "otp_codes" (
    "id" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "isUsed" BOOLEAN NOT NULL DEFAULT false,
    "purpose" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "userId" TEXT NOT NULL,

    CONSTRAINT "otp_codes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sessions" (
    "id" TEXT NOT NULL,
    "token" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "userId" TEXT NOT NULL,

    CONSTRAINT "sessions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "user_addresses" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "chainType" TEXT NOT NULL,
    "chainId" INTEGER,
    "address" TEXT NOT NULL,
    "addressFormat" TEXT NOT NULL,
    "derivationPath" TEXT NOT NULL,
    "curve" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "isPrimary" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "user_addresses_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "wallets" (
    "id" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "name" TEXT NOT NULL DEFAULT 'My Wallet',
    "userId" TEXT NOT NULL,
    "chainId" INTEGER NOT NULL DEFAULT 42161,
    "walletType" TEXT NOT NULL DEFAULT 'smart_wallet',
    "deploymentStatus" TEXT NOT NULL DEFAULT 'counterfactual',
    "nonce" BIGINT NOT NULL DEFAULT 0,
    "factoryAddress" TEXT,
    "ownerAddress" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "lastActivityAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "metadata" JSONB NOT NULL DEFAULT '{}',
    "totalGasUsed" DECIMAL(30,0) NOT NULL DEFAULT 0,
    "totalGasCostUsd" DECIMAL(20,8) NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "wallets_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "balances" (
    "id" TEXT NOT NULL,
    "walletId" TEXT NOT NULL,
    "tokenAddress" TEXT NOT NULL DEFAULT 'native',
    "balance" DECIMAL(78,18) NOT NULL DEFAULT 0,
    "chainId" INTEGER NOT NULL DEFAULT 42161,
    "tokenName" TEXT,
    "tokenSymbol" TEXT,
    "tokenDecimals" INTEGER NOT NULL DEFAULT 18,
    "tokenIconUrl" TEXT,
    "balanceUsd" DECIMAL(20,8) NOT NULL DEFAULT 0,
    "pricePerTokenUsd" DECIMAL(20,8) NOT NULL DEFAULT 0,
    "isVerified" BOOLEAN NOT NULL DEFAULT false,
    "isSpam" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "balances_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "transactions" (
    "id" TEXT NOT NULL,
    "walletId" TEXT NOT NULL,
    "hash" TEXT,
    "fromAddress" TEXT,
    "toAddress" TEXT,
    "value" DECIMAL(78,18),
    "status" TEXT NOT NULL DEFAULT 'pending',
    "chainId" INTEGER NOT NULL DEFAULT 42161,
    "transactionType" TEXT NOT NULL DEFAULT 'transfer',
    "gasLimit" BIGINT,
    "gasUsed" BIGINT,
    "gasPrice" DECIMAL(30,0),
    "maxFeePerGas" DECIMAL(30,0),
    "maxPriorityFeePerGas" DECIMAL(30,0),
    "gasCostWei" DECIMAL(30,0),
    "gasCostUsd" DECIMAL(20,8),
    "blockNumber" BIGINT,
    "blockTimestamp" TIMESTAMP(3),
    "confirmationCount" INTEGER NOT NULL DEFAULT 0,
    "tokenAddress" TEXT,
    "tokenAmount" DECIMAL(30,0),
    "metadata" JSONB NOT NULL DEFAULT '{}',
    "errorMessage" TEXT,
    "internalTransactions" JSONB NOT NULL DEFAULT '[]',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "transactions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "networks" (
    "id" TEXT NOT NULL,
    "chainId" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "shortName" TEXT NOT NULL,
    "currencySymbol" TEXT NOT NULL,
    "rpcUrl" TEXT NOT NULL,
    "explorerUrl" TEXT,
    "iconUrl" TEXT,
    "isTestnet" BOOLEAN NOT NULL DEFAULT false,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "entryPointAddress" TEXT,
    "walletFactoryAddress" TEXT,
    "blockTimeSeconds" INTEGER NOT NULL DEFAULT 12,
    "confirmationBlocks" INTEGER NOT NULL DEFAULT 12,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "networks_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "token_metadata" (
    "id" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "chainId" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "symbol" TEXT NOT NULL,
    "decimals" INTEGER NOT NULL,
    "iconUrl" TEXT,
    "isVerified" BOOLEAN NOT NULL DEFAULT false,
    "isSpam" BOOLEAN NOT NULL DEFAULT false,
    "totalSupply" DECIMAL(30,0),
    "marketCapUsd" DECIMAL(20,2),
    "priceUsd" DECIMAL(20,8),
    "priceChange24h" DECIMAL(10,4),
    "volume24hUsd" DECIMAL(20,2),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "token_metadata_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "cross_chain_transactions" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "sourceWalletId" TEXT NOT NULL,
    "sourceChainId" INTEGER NOT NULL,
    "destinationChainId" INTEGER NOT NULL,
    "sourceTxHash" TEXT,
    "destinationTxHash" TEXT,
    "tokenAddress" TEXT,
    "amount" DECIMAL(30,0) NOT NULL,
    "bridgeProvider" TEXT,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "estimatedTimeMinutes" INTEGER,
    "actualTimeMinutes" INTEGER,
    "bridgeFeeUsd" DECIMAL(20,8),
    "exchangeRate" DECIMAL(20,8),
    "metadata" JSONB NOT NULL DEFAULT '{}',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "cross_chain_transactions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "wallet_activity" (
    "id" TEXT NOT NULL,
    "walletId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "activityType" TEXT NOT NULL,
    "chainId" INTEGER NOT NULL,
    "transactionHash" TEXT,
    "amount" DECIMAL(30,0),
    "tokenAddress" TEXT,
    "metadata" JSONB NOT NULL DEFAULT '{}',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "wallet_activity_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "gas_analytics" (
    "id" TEXT NOT NULL,
    "walletId" TEXT NOT NULL,
    "chainId" INTEGER NOT NULL,
    "transactionType" TEXT NOT NULL,
    "gasLimit" BIGINT NOT NULL,
    "gasUsed" BIGINT NOT NULL,
    "gasPrice" DECIMAL(30,0) NOT NULL,
    "gasCostWei" DECIMAL(30,0) NOT NULL,
    "gasCostUsd" DECIMAL(20,8),
    "blockNumber" BIGINT,
    "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "gas_analytics_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "session_keys" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "walletId" TEXT NOT NULL,
    "walletAddress" TEXT NOT NULL,
    "sessionKey" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "permissions" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastUsedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "turnkeySignerId" TEXT,
    "turnkeySubOrgId" TEXT,
    "maxValue" DECIMAL(30,0),
    "allowedTargets" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "rateLimit" JSONB DEFAULT '{}',

    CONSTRAINT "session_keys_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "turnkey_signers" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "walletId" TEXT,
    "turnkeyUserId" TEXT NOT NULL,
    "turnkeySubOrgId" TEXT NOT NULL,
    "publicKey" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "phoneHash" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "passkeyConfig" JSONB DEFAULT '{}',
    "authMethods" TEXT[] DEFAULT ARRAY['passkey']::TEXT[],

    CONSTRAINT "turnkey_signers_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "kernel_accounts" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "walletId" TEXT NOT NULL,
    "chainId" INTEGER NOT NULL,
    "address" TEXT NOT NULL,
    "ownerAddress" TEXT NOT NULL,
    "index" INTEGER NOT NULL DEFAULT 0,
    "isDeployed" BOOLEAN NOT NULL DEFAULT false,
    "deploymentHash" TEXT,
    "turnkeyUserId" TEXT,
    "turnkeySubOrgId" TEXT,
    "factoryAddress" TEXT,
    "initCode" TEXT,
    "signerVersion" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "kernel_accounts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "user_operations" (
    "id" TEXT NOT NULL,
    "walletId" TEXT NOT NULL,
    "chainId" INTEGER NOT NULL,
    "userOpHash" TEXT NOT NULL,
    "transactionHash" TEXT,
    "blockNumber" INTEGER,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "gasUsed" INTEGER,
    "gasCostUsd" DECIMAL(20,8),
    "transactions" JSONB NOT NULL,
    "metadata" JSONB DEFAULT '{}',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "user_operations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "notifications" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "message" TEXT NOT NULL,
    "type" "NotificationType" NOT NULL,
    "isRead" BOOLEAN NOT NULL DEFAULT false,
    "data" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "notifications_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "notification_settings" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "pushEnabled" BOOLEAN NOT NULL DEFAULT true,
    "emailEnabled" BOOLEAN NOT NULL DEFAULT true,
    "transactionAlerts" BOOLEAN NOT NULL DEFAULT true,
    "securityAlerts" BOOLEAN NOT NULL DEFAULT true,
    "marketingAlerts" BOOLEAN NOT NULL DEFAULT false,
    "priceAlerts" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "notification_settings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "devices" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "token" TEXT NOT NULL,
    "deviceType" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "lastUsed" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "devices_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "passkey_credentials" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "credentialId" TEXT NOT NULL,
    "publicKey" TEXT NOT NULL,
    "publicKeyFormat" TEXT,
    "turnkeySubOrgId" TEXT,
    "supportedChains" TEXT[] DEFAULT ARRAY['ETHEREUM', 'BNB', 'SOLANA', 'BITCOIN']::TEXT[],
    "authLevel" TEXT DEFAULT 'BIOMETRIC_ONLY',
    "dailyLimitUsd" DECIMAL(20,2) DEFAULT 1000.00,
    "turnkeyUserId" TEXT,
    "turnkeyWalletId" TEXT,
    "walletAddress" TEXT,
    "counter" INTEGER NOT NULL DEFAULT 0,
    "riskScore" INTEGER DEFAULT 0,
    "lastUsedAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "deviceFingerprint" JSONB DEFAULT '{}',
    "recoveryConfig" JSONB DEFAULT '{}',
    "isRecoveryKey" BOOLEAN DEFAULT false,
    "deviceName" TEXT,
    "deviceType" TEXT,
    "deviceModel" TEXT,
    "biometricType" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "passkey_credentials_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "passkey_sessions" (
    "id" TEXT NOT NULL,
    "passkeyCredentialId" TEXT NOT NULL,
    "sessionKeyPublic" TEXT NOT NULL,
    "permissions" JSONB NOT NULL,
    "dailySpentUsd" DECIMAL(20,2) NOT NULL DEFAULT 0,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "chainId" INTEGER NOT NULL,
    "ipAddress" TEXT,
    "userAgent" TEXT,
    "lastUsedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "passkey_sessions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "social_recovery_guardians" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "guardianAddress" TEXT NOT NULL,
    "guardianType" TEXT NOT NULL,
    "guardianName" TEXT,
    "threshold" INTEGER NOT NULL,
    "weight" INTEGER NOT NULL DEFAULT 1,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "contactInfo" JSONB,
    "lastContactedAt" TIMESTAMP(3),
    "recoveryAttempts" INTEGER NOT NULL DEFAULT 0,
    "addedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "social_recovery_guardians_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "recovery_sessions" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "initiatedByGuardianId" TEXT NOT NULL,
    "recoveryReason" TEXT NOT NULL,
    "newCredentialId" TEXT,
    "requiredVotes" INTEGER NOT NULL,
    "currentVotes" INTEGER NOT NULL DEFAULT 0,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "challengeHash" TEXT NOT NULL,
    "verificationCode" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completedAt" TIMESTAMP(3),

    CONSTRAINT "recovery_sessions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "passkey_security_events" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "passkeyCredentialId" TEXT,
    "eventType" TEXT NOT NULL,
    "eventSeverity" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "ipAddress" TEXT,
    "userAgent" TEXT,
    "location" JSONB,
    "deviceFingerprint" JSONB,
    "riskScore" INTEGER NOT NULL DEFAULT 0,
    "anomalyFlags" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "actionTaken" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "passkey_security_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "auth_challenges" (
    "id" TEXT NOT NULL,
    "challengeId" TEXT NOT NULL,
    "challenge" TEXT NOT NULL,
    "userId" TEXT,
    "phoneNumber" TEXT,
    "firstName" TEXT,
    "lastName" TEXT,
    "email" TEXT,
    "type" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expiresAt" TIMESTAMP(3) NOT NULL DEFAULT (now() + interval '10 minutes'),

    CONSTRAINT "auth_challenges_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "webauthn_challenges" (
    "id" TEXT NOT NULL,
    "challenge" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "purpose" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expiresAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "webauthn_challenges_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "momo_providers" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "displayName" TEXT NOT NULL,
    "country" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "apiConfig" JSONB NOT NULL,
    "onRampFeePercent" DECIMAL(5,4) NOT NULL DEFAULT 0.01,
    "offRampFeePercent" DECIMAL(5,4) NOT NULL DEFAULT 0.015,
    "fixedFeeAmount" DECIMAL(10,2) NOT NULL DEFAULT 0,
    "minTransactionAmount" DECIMAL(20,8) NOT NULL DEFAULT 500,
    "maxTransactionAmount" DECIMAL(20,8) NOT NULL DEFAULT 1000000,
    "dailyLimit" DECIMAL(20,8) NOT NULL DEFAULT 2000000,
    "monthlyLimit" DECIMAL(20,8) NOT NULL DEFAULT 50000000,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "momo_providers_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "momo_transactions" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "walletAddress" TEXT NOT NULL,
    "providerId" TEXT NOT NULL,
    "providerCode" TEXT,
    "paymentMethod" "PaymentMethod" NOT NULL DEFAULT 'OTP_PAYMENT',
    "lifecycleStage" TEXT NOT NULL DEFAULT 'CREATED',
    "type" "TransactionType" NOT NULL,
    "status" "TransactionStatus" NOT NULL DEFAULT 'PENDING',
    "amount" DECIMAL(20,8) NOT NULL,
    "currency" TEXT NOT NULL,
    "cryptoAmount" DECIMAL(20,8),
    "cryptoCurrency" TEXT,
    "exchangeRate" DECIMAL(20,8),
    "providerTxId" TEXT,
    "providerRef" TEXT,
    "phoneNumber" TEXT NOT NULL,
    "otpCode" TEXT,
    "otpVerifiedAt" TIMESTAMP(3),
    "otpExpiry" TIMESTAMP(3),
    "isVerified" BOOLEAN NOT NULL DEFAULT false,
    "encryptedPinUsed" BOOLEAN NOT NULL DEFAULT false,
    "currentState" TEXT NOT NULL DEFAULT 'CREATED',
    "stateUpdatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "payToken" TEXT,
    "notifToken" TEXT,
    "ussdTimeoutAt" TIMESTAMP(3),
    "idempotencyKey" TEXT,
    "pollingAttempts" INTEGER NOT NULL DEFAULT 0,
    "lastPollingAt" TIMESTAMP(3),
    "refundTxHash" TEXT,
    "refundedAt" TIMESTAMP(3),
    "refundReason" TEXT,
    "blockchainTxHash" TEXT,
    "blockNumber" BIGINT,
    "gasUsed" BIGINT,
    "gasFee" DECIMAL(20,8),
    "isReconciled" BOOLEAN NOT NULL DEFAULT false,
    "reconciledAt" TIMESTAMP(3),
    "complianceStatus" "ComplianceStatus" NOT NULL DEFAULT 'PENDING',
    "complianceNotes" TEXT,
    "metadata" JSONB,
    "failureReason" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "momo_transactions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "transaction_fees" (
    "id" TEXT NOT NULL,
    "transactionId" TEXT NOT NULL,
    "providerId" TEXT NOT NULL,
    "feeType" "FeeType" NOT NULL,
    "amount" DECIMAL(20,8) NOT NULL,
    "currency" TEXT NOT NULL,
    "percentage" DECIMAL(5,4),
    "gasPrice" DECIMAL(20,8),
    "gasLimit" BIGINT,
    "gasUsed" BIGINT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "transaction_fees_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "wallet_momo_mappings" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "walletAddress" TEXT NOT NULL,
    "providerId" TEXT NOT NULL,
    "phoneNumber" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "isVerified" BOOLEAN NOT NULL DEFAULT false,
    "kycStatus" "KycStatus" NOT NULL DEFAULT 'PENDING',
    "kycLevel" INTEGER NOT NULL DEFAULT 1,
    "verifiedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "wallet_momo_mappings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "transaction_limits" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "providerId" TEXT NOT NULL,
    "dailyUsed" DECIMAL(20,8) NOT NULL DEFAULT 0,
    "monthlyUsed" DECIMAL(20,8) NOT NULL DEFAULT 0,
    "lastDailyReset" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastMonthlyReset" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "customDailyLimit" DECIMAL(20,8),
    "customMonthlyLimit" DECIMAL(20,8),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "transaction_limits_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "webhook_deliveries" (
    "id" TEXT NOT NULL,
    "transactionId" TEXT NOT NULL,
    "webhookUrl" TEXT NOT NULL,
    "eventType" TEXT NOT NULL,
    "payload" JSONB NOT NULL,
    "status" "WebhookStatus" NOT NULL DEFAULT 'PENDING',
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "maxAttempts" INTEGER NOT NULL DEFAULT 3,
    "lastAttempt" TIMESTAMP(3),
    "nextAttempt" TIMESTAMP(3),
    "responseCode" INTEGER,
    "responseBody" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "webhook_deliveries_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "transaction_state_history" (
    "id" TEXT NOT NULL,
    "transactionId" TEXT NOT NULL,
    "previousState" TEXT,
    "currentState" TEXT NOT NULL,
    "trigger" TEXT NOT NULL,
    "verificationData" JSONB,
    "errorMessage" TEXT,
    "metadata" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "transaction_state_history_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "idempotency_keys" (
    "id" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "transactionId" TEXT,
    "requestHash" TEXT NOT NULL,
    "responseData" JSONB,
    "status" "IdempotencyStatus" NOT NULL DEFAULT 'PENDING',
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "idempotency_keys_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "oauth_token_cache" (
    "id" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "accessToken" TEXT NOT NULL,
    "refreshToken" TEXT,
    "tokenType" TEXT NOT NULL DEFAULT 'Bearer',
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "scopes" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "metadata" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "oauth_token_cache_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "orange_public_key_cache" (
    "id" TEXT NOT NULL,
    "keyId" TEXT NOT NULL,
    "publicKey" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "orange_public_key_cache_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "queue_jobs" (
    "id" TEXT NOT NULL,
    "jobId" TEXT NOT NULL,
    "queueName" TEXT NOT NULL,
    "transactionId" TEXT,
    "jobType" TEXT NOT NULL,
    "status" "QueueJobStatus" NOT NULL DEFAULT 'PENDING',
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "maxAttempts" INTEGER NOT NULL DEFAULT 3,
    "lastAttemptAt" TIMESTAMP(3),
    "nextAttemptAt" TIMESTAMP(3),
    "resultData" JSONB,
    "errorMessage" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "queue_jobs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "treasury_ledger" (
    "id" TEXT NOT NULL,
    "transactionId" TEXT NOT NULL,
    "debitAccount" TEXT NOT NULL,
    "creditAccount" TEXT NOT NULL,
    "amount" DECIMAL(30,18) NOT NULL,
    "currency" TEXT NOT NULL,
    "entryType" "LedgerEntryType" NOT NULL,
    "txHash" TEXT,
    "chainId" INTEGER,
    "blockNumber" BIGINT,
    "confirmations" INTEGER NOT NULL DEFAULT 0,
    "status" "LedgerEntryStatus" NOT NULL DEFAULT 'PENDING',
    "errorMessage" TEXT,
    "description" TEXT,
    "fiatAmount" DECIMAL(20,8),
    "fiatCurrency" TEXT,
    "exchangeRate" DECIMAL(20,8),
    "provider" TEXT,
    "metadata" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdBy" TEXT,

    CONSTRAINT "treasury_ledger_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "liquidity_pools" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "currency" TEXT NOT NULL,
    "cryptoCurrency" TEXT NOT NULL,
    "fiatBalance" DECIMAL(20,8) NOT NULL,
    "cryptoBalance" DECIMAL(20,8) NOT NULL,
    "minReserveRatio" DECIMAL(5,4) NOT NULL,
    "maxSlippage" DECIMAL(5,4) NOT NULL,
    "dexAddress" TEXT,
    "poolAddress" TEXT,
    "lastRebalance" TIMESTAMP(3),
    "autoRebalance" BOOLEAN NOT NULL DEFAULT false,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "liquidity_pools_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "exchange_rates" (
    "id" TEXT NOT NULL,
    "fromCurrency" TEXT NOT NULL,
    "toCurrency" TEXT NOT NULL,
    "rate" DECIMAL(20,8) NOT NULL,
    "source" TEXT NOT NULL,
    "bid" DECIMAL(20,8),
    "ask" DECIMAL(20,8),
    "spread" DECIMAL(5,4),
    "volume24h" DECIMAL(20,8),
    "expiresAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "exchange_rates_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "audit_logs" (
    "id" TEXT NOT NULL,
    "userId" TEXT,
    "action" TEXT NOT NULL,
    "entityType" TEXT NOT NULL,
    "entityId" TEXT NOT NULL,
    "oldValues" JSONB,
    "newValues" JSONB,
    "ipAddress" TEXT,
    "userAgent" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "agent_audit_logs" (
    "id" TEXT NOT NULL,
    "missionId" TEXT,
    "userId" TEXT,
    "node" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "asset" TEXT,
    "llmPrompt" TEXT,
    "llmResponse" TEXT,
    "llmModel" TEXT,
    "llmTokens" INTEGER,
    "decision" JSONB,
    "reasoning" TEXT,
    "metadata" JSONB,
    "success" BOOLEAN NOT NULL DEFAULT true,
    "errorMessage" TEXT,
    "dryRun" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "agent_audit_logs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "commission_records" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "transactionId" TEXT NOT NULL,
    "type" "CommissionType" NOT NULL,
    "grossAmount" DOUBLE PRECISION NOT NULL,
    "commission" DOUBLE PRECISION NOT NULL,
    "netAmount" DOUBLE PRECISION NOT NULL,
    "currency" TEXT NOT NULL,
    "provider" TEXT,
    "blockchainTxHash" TEXT,
    "metadata" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "commission_records_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "morpho_transactions" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" "MorphoTransactionType" NOT NULL,
    "marketId" TEXT,
    "vaultAddress" TEXT,
    "amount" TEXT NOT NULL,
    "asset" TEXT NOT NULL,
    "blockHash" TEXT,
    "transactionHash" TEXT,
    "blockNumber" BIGINT,
    "gasUsed" TEXT,
    "status" "MorphoTransactionStatus" NOT NULL DEFAULT 'PENDING',
    "commission" TEXT,
    "commissionRate" DOUBLE PRECISION,
    "metadata" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "morpho_transactions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "morpho_market_positions" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "marketId" TEXT NOT NULL,
    "userAddress" TEXT NOT NULL,
    "supplyShares" TEXT NOT NULL DEFAULT '0',
    "borrowShares" TEXT NOT NULL DEFAULT '0',
    "collateral" TEXT NOT NULL DEFAULT '0',
    "lastUpdate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "metadata" JSONB,

    CONSTRAINT "morpho_market_positions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "morpho_vault_positions" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "vaultAddress" TEXT NOT NULL,
    "userAddress" TEXT NOT NULL,
    "shares" TEXT NOT NULL DEFAULT '0',
    "assets" TEXT NOT NULL DEFAULT '0',
    "lastUpdate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "metadata" JSONB,

    CONSTRAINT "morpho_vault_positions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "morpho_markets" (
    "id" TEXT NOT NULL,
    "loanToken" TEXT NOT NULL,
    "collateralToken" TEXT NOT NULL,
    "oracle" TEXT NOT NULL,
    "irm" TEXT NOT NULL,
    "lltv" TEXT NOT NULL,
    "totalSupply" TEXT NOT NULL DEFAULT '0',
    "totalBorrow" TEXT NOT NULL DEFAULT '0',
    "supplyApy" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "borrowApy" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "utilizationRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "liquidity" TEXT NOT NULL DEFAULT '0',
    "lastUpdate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "metadata" JSONB,

    CONSTRAINT "morpho_markets_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "morpho_vaults" (
    "id" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "symbol" TEXT NOT NULL,
    "asset" TEXT NOT NULL,
    "totalSupply" TEXT NOT NULL DEFAULT '0',
    "totalAssets" TEXT NOT NULL DEFAULT '0',
    "apy" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "curator" TEXT NOT NULL,
    "owner" TEXT NOT NULL,
    "timelock" BIGINT NOT NULL DEFAULT 0,
    "lastUpdate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "metadata" JSONB,

    CONSTRAINT "morpho_vaults_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "defi_bundled_operations" (
    "id" TEXT NOT NULL,
    "walletId" TEXT NOT NULL,
    "chainId" INTEGER NOT NULL,
    "userOpHash" TEXT NOT NULL,
    "protocol" TEXT NOT NULL,
    "operations" JSONB NOT NULL,
    "callsCount" INTEGER NOT NULL,
    "status" "DeFiBundleStatus" NOT NULL DEFAULT 'PENDING',
    "gasUsed" TEXT,
    "blockNumber" BIGINT,
    "transactionHash" TEXT,
    "metadata" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "defi_bundled_operations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "defi_protocol_integrations" (
    "id" TEXT NOT NULL,
    "protocol" TEXT NOT NULL,
    "chainId" INTEGER NOT NULL,
    "contractAddress" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "configuration" JSONB NOT NULL,
    "supportedOperations" TEXT[],
    "gasOptimizations" JSONB,
    "lastUpdate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "metadata" JSONB,

    CONSTRAINT "defi_protocol_integrations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "agent_missions" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "walletId" TEXT NOT NULL,
    "turnkeySignerId" TEXT,
    "agentAddress" TEXT,
    "agentPrivateKeyEnc" TEXT,
    "agentKeyIv" TEXT,
    "agentKeyTag" TEXT,
    "hyperliquidApproved" BOOLEAN NOT NULL DEFAULT false,
    "approvalTxHash" TEXT,
    "masterEoaAddress" TEXT,
    "masterEoaKeyEnc" TEXT,
    "vaultKeyCreated" BOOLEAN NOT NULL DEFAULT false,
    "vaultKeyDestroyed" BOOLEAN NOT NULL DEFAULT false,
    "finalBalance" DECIMAL(20,8),
    "protocolFee" DECIMAL(20,8),
    "userPayout" DECIMAL(20,8),
    "feeCollectedAt" TIMESTAMP(3),
    "payoutCompletedAt" TIMESTAMP(3),
    "strategy" "StrategyType" NOT NULL DEFAULT 'SHORT_TERM_30D',
    "riskLevel" "AgentRiskLevel" NOT NULL DEFAULT 'MODERATE',
    "durationDays" INTEGER NOT NULL DEFAULT 30,
    "startedAt" TIMESTAMP(3),
    "endsAt" TIMESTAMP(3),
    "initialCapital" DECIMAL(20,8) NOT NULL,
    "currentValue" DECIMAL(20,8),
    "depositCurrency" TEXT NOT NULL DEFAULT 'USDC',
    "maxLeverage" INTEGER NOT NULL DEFAULT 3,
    "allowedAssets" TEXT[] DEFAULT ARRAY['ETH-USD', 'BTC-USD']::TEXT[],
    "status" "MissionStatus" NOT NULL DEFAULT 'PENDING',
    "pausedAt" TIMESTAMP(3),
    "completedAt" TIMESTAMP(3),
    "totalPnl" DECIMAL(20,8) NOT NULL DEFAULT 0,
    "totalTrades" INTEGER NOT NULL DEFAULT 0,
    "winRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "maxDrawdown" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "metadata" JSONB DEFAULT '{}',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "agent_missions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "agent_signals" (
    "id" TEXT NOT NULL,
    "signalId" TEXT NOT NULL,
    "direction" "TradeDirection" NOT NULL,
    "asset" TEXT NOT NULL,
    "confidence" "ConfidenceLevel" NOT NULL,
    "recommendedLeverage" INTEGER NOT NULL DEFAULT 1,
    "reasoning" TEXT NOT NULL,
    "strategyTag" TEXT NOT NULL,
    "ragContextIds" TEXT[],
    "maxDrawdown30d" DOUBLE PRECISION,
    "volatilityScore" DOUBLE PRECISION,
    "generatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "isProcessed" BOOLEAN NOT NULL DEFAULT false,
    "processedAt" TIMESTAMP(3),
    "usersNotified" INTEGER NOT NULL DEFAULT 0,
    "ordersGenerated" INTEGER NOT NULL DEFAULT 0,
    "ordersExecuted" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "agent_signals_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "agent_positions" (
    "id" TEXT NOT NULL,
    "missionId" TEXT NOT NULL,
    "signalId" TEXT,
    "asset" TEXT NOT NULL,
    "direction" "TradeDirection" NOT NULL,
    "entryPrice" DECIMAL(20,8) NOT NULL,
    "currentPrice" DECIMAL(20,8) NOT NULL,
    "quantity" DECIMAL(20,8) NOT NULL,
    "leverage" INTEGER NOT NULL DEFAULT 1,
    "hyperliquidOrderId" TEXT,
    "marginUsed" DECIMAL(20,8) NOT NULL,
    "liquidationPrice" DECIMAL(20,8),
    "unrealizedPnl" DECIMAL(20,8) NOT NULL DEFAULT 0,
    "realizedPnl" DECIMAL(20,8) NOT NULL DEFAULT 0,
    "fundingPaid" DECIMAL(20,8) NOT NULL DEFAULT 0,
    "status" "PositionStatus" NOT NULL DEFAULT 'OPEN',
    "openedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "closedAt" TIMESTAMP(3),
    "closeReason" TEXT,
    "stopLossPrice" DECIMAL(20,8),
    "takeProfitPrice" DECIMAL(20,8),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "agent_positions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "agent_trade_executions" (
    "id" TEXT NOT NULL,
    "missionId" TEXT NOT NULL,
    "signalId" TEXT,
    "action" TEXT NOT NULL,
    "asset" TEXT NOT NULL,
    "quantity" DECIMAL(20,8),
    "price" DECIMAL(20,8),
    "missionDay" INTEGER,
    "decisionReason" TEXT,
    "userBalanceAtTime" DECIMAL(20,8),
    "success" BOOLEAN NOT NULL,
    "hyperliquidTxHash" TEXT,
    "errorMessage" TEXT,
    "isDryRun" BOOLEAN NOT NULL DEFAULT false,
    "executedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "agent_trade_executions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "agent_pnl_snapshots" (
    "id" TEXT NOT NULL,
    "missionId" TEXT NOT NULL,
    "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "totalValue" DECIMAL(20,8) NOT NULL,
    "totalPnl" DECIMAL(20,8) NOT NULL,
    "unrealizedPnl" DECIMAL(20,8) NOT NULL,
    "realizedPnl" DECIMAL(20,8) NOT NULL,

    CONSTRAINT "agent_pnl_snapshots_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "platform_fee_records" (
    "id" TEXT NOT NULL,
    "missionId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "initialCapital" DECIMAL(20,8) NOT NULL,
    "finalBalance" DECIMAL(20,8) NOT NULL,
    "profit" DECIMAL(20,8) NOT NULL,
    "feePercent" DOUBLE PRECISION NOT NULL DEFAULT 30,
    "feeAmount" DECIMAL(20,8) NOT NULL,
    "feeTxHash" TEXT,
    "payoutTxHash" TEXT,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "platform_fee_records_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "_GuardianVotes" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,

    CONSTRAINT "_GuardianVotes_AB_pkey" PRIMARY KEY ("A","B")
);

-- CreateIndex
CREATE UNIQUE INDEX "users_phoneNumber_key" ON "users"("phoneNumber");

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- CreateIndex
CREATE UNIQUE INDEX "users_walletAddress_key" ON "users"("walletAddress");

-- CreateIndex
CREATE UNIQUE INDEX "users_idNumber_key" ON "users"("idNumber");

-- CreateIndex
CREATE UNIQUE INDEX "users_turnkeySubOrgId_key" ON "users"("turnkeySubOrgId");

-- CreateIndex
CREATE UNIQUE INDEX "sessions_token_key" ON "sessions"("token");

-- CreateIndex
CREATE UNIQUE INDEX "user_addresses_userId_chainType_isPrimary_key" ON "user_addresses"("userId", "chainType", "isPrimary");

-- CreateIndex
CREATE UNIQUE INDEX "wallets_address_chainId_key" ON "wallets"("address", "chainId");

-- CreateIndex
CREATE UNIQUE INDEX "transactions_hash_key" ON "transactions"("hash");

-- CreateIndex
CREATE UNIQUE INDEX "networks_chainId_key" ON "networks"("chainId");

-- CreateIndex
CREATE UNIQUE INDEX "token_metadata_address_chainId_key" ON "token_metadata"("address", "chainId");

-- CreateIndex
CREATE UNIQUE INDEX "session_keys_sessionKey_key" ON "session_keys"("sessionKey");

-- CreateIndex
CREATE INDEX "session_keys_userId_walletId_idx" ON "session_keys"("userId", "walletId");

-- CreateIndex
CREATE INDEX "session_keys_walletAddress_isActive_idx" ON "session_keys"("walletAddress", "isActive");

-- CreateIndex
CREATE INDEX "session_keys_expiresAt_isActive_idx" ON "session_keys"("expiresAt", "isActive");

-- CreateIndex
CREATE UNIQUE INDEX "turnkey_signers_turnkeyUserId_key" ON "turnkey_signers"("turnkeyUserId");

-- CreateIndex
CREATE UNIQUE INDEX "turnkey_signers_turnkeySubOrgId_key" ON "turnkey_signers"("turnkeySubOrgId");

-- CreateIndex
CREATE UNIQUE INDEX "turnkey_signers_address_key" ON "turnkey_signers"("address");

-- CreateIndex
CREATE INDEX "turnkey_signers_userId_idx" ON "turnkey_signers"("userId");

-- CreateIndex
CREATE INDEX "turnkey_signers_walletId_idx" ON "turnkey_signers"("walletId");

-- CreateIndex
CREATE INDEX "turnkey_signers_phoneHash_idx" ON "turnkey_signers"("phoneHash");

-- CreateIndex
CREATE INDEX "kernel_accounts_userId_chainId_idx" ON "kernel_accounts"("userId", "chainId");

-- CreateIndex
CREATE INDEX "kernel_accounts_walletId_chainId_idx" ON "kernel_accounts"("walletId", "chainId");

-- CreateIndex
CREATE UNIQUE INDEX "kernel_accounts_address_chainId_key" ON "kernel_accounts"("address", "chainId");

-- CreateIndex
CREATE UNIQUE INDEX "user_operations_userOpHash_key" ON "user_operations"("userOpHash");

-- CreateIndex
CREATE INDEX "user_operations_walletId_chainId_idx" ON "user_operations"("walletId", "chainId");

-- CreateIndex
CREATE INDEX "user_operations_userOpHash_idx" ON "user_operations"("userOpHash");

-- CreateIndex
CREATE INDEX "user_operations_transactionHash_idx" ON "user_operations"("transactionHash");

-- CreateIndex
CREATE INDEX "user_operations_status_createdAt_idx" ON "user_operations"("status", "createdAt");

-- CreateIndex
CREATE UNIQUE INDEX "notification_settings_userId_key" ON "notification_settings"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "devices_token_key" ON "devices"("token");

-- CreateIndex
CREATE UNIQUE INDEX "passkey_credentials_credentialId_key" ON "passkey_credentials"("credentialId");

-- CreateIndex
CREATE INDEX "passkey_credentials_userId_idx" ON "passkey_credentials"("userId");

-- CreateIndex
CREATE INDEX "passkey_credentials_turnkeySubOrgId_idx" ON "passkey_credentials"("turnkeySubOrgId");

-- CreateIndex
CREATE INDEX "passkey_credentials_credentialId_idx" ON "passkey_credentials"("credentialId");

-- CreateIndex
CREATE INDEX "passkey_credentials_userId_createdAt_idx" ON "passkey_credentials"("userId", "createdAt");

-- CreateIndex
CREATE INDEX "passkey_sessions_passkeyCredentialId_idx" ON "passkey_sessions"("passkeyCredentialId");

-- CreateIndex
CREATE INDEX "passkey_sessions_expiresAt_idx" ON "passkey_sessions"("expiresAt");

-- CreateIndex
CREATE INDEX "social_recovery_guardians_userId_idx" ON "social_recovery_guardians"("userId");

-- CreateIndex
CREATE INDEX "social_recovery_guardians_guardianAddress_idx" ON "social_recovery_guardians"("guardianAddress");

-- CreateIndex
CREATE INDEX "recovery_sessions_userId_idx" ON "recovery_sessions"("userId");

-- CreateIndex
CREATE INDEX "recovery_sessions_status_expiresAt_idx" ON "recovery_sessions"("status", "expiresAt");

-- CreateIndex
CREATE INDEX "passkey_security_events_userId_createdAt_idx" ON "passkey_security_events"("userId", "createdAt");

-- CreateIndex
CREATE INDEX "passkey_security_events_eventType_eventSeverity_idx" ON "passkey_security_events"("eventType", "eventSeverity");

-- CreateIndex
CREATE INDEX "passkey_security_events_riskScore_idx" ON "passkey_security_events"("riskScore");

-- CreateIndex
CREATE UNIQUE INDEX "auth_challenges_challengeId_key" ON "auth_challenges"("challengeId");

-- CreateIndex
CREATE INDEX "auth_challenges_challengeId_idx" ON "auth_challenges"("challengeId");

-- CreateIndex
CREATE INDEX "auth_challenges_expiresAt_idx" ON "auth_challenges"("expiresAt");

-- CreateIndex
CREATE INDEX "auth_challenges_phoneNumber_idx" ON "auth_challenges"("phoneNumber");

-- CreateIndex
CREATE INDEX "auth_challenges_userId_idx" ON "auth_challenges"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "webauthn_challenges_challenge_key" ON "webauthn_challenges"("challenge");

-- CreateIndex
CREATE INDEX "webauthn_challenges_userId_type_idx" ON "webauthn_challenges"("userId", "type");

-- CreateIndex
CREATE INDEX "webauthn_challenges_challenge_expiresAt_idx" ON "webauthn_challenges"("challenge", "expiresAt");

-- CreateIndex
CREATE UNIQUE INDEX "momo_providers_name_key" ON "momo_providers"("name");

-- CreateIndex
CREATE UNIQUE INDEX "momo_transactions_idempotencyKey_key" ON "momo_transactions"("idempotencyKey");

-- CreateIndex
CREATE INDEX "momo_transactions_userId_createdAt_idx" ON "momo_transactions"("userId", "createdAt");

-- CreateIndex
CREATE INDEX "momo_transactions_status_createdAt_idx" ON "momo_transactions"("status", "createdAt");

-- CreateIndex
CREATE INDEX "momo_transactions_providerTxId_idx" ON "momo_transactions"("providerTxId");

-- CreateIndex
CREATE INDEX "momo_transactions_blockchainTxHash_idx" ON "momo_transactions"("blockchainTxHash");

-- CreateIndex
CREATE INDEX "momo_transactions_currentState_createdAt_idx" ON "momo_transactions"("currentState", "createdAt");

-- CreateIndex
CREATE INDEX "momo_transactions_idempotencyKey_idx" ON "momo_transactions"("idempotencyKey");

-- CreateIndex
CREATE INDEX "wallet_momo_mappings_phoneNumber_idx" ON "wallet_momo_mappings"("phoneNumber");

-- CreateIndex
CREATE UNIQUE INDEX "wallet_momo_mappings_userId_providerId_key" ON "wallet_momo_mappings"("userId", "providerId");

-- CreateIndex
CREATE UNIQUE INDEX "transaction_limits_userId_providerId_key" ON "transaction_limits"("userId", "providerId");

-- CreateIndex
CREATE INDEX "webhook_deliveries_status_nextAttempt_idx" ON "webhook_deliveries"("status", "nextAttempt");

-- CreateIndex
CREATE INDEX "transaction_state_history_transactionId_createdAt_idx" ON "transaction_state_history"("transactionId", "createdAt");

-- CreateIndex
CREATE UNIQUE INDEX "idempotency_keys_key_key" ON "idempotency_keys"("key");

-- CreateIndex
CREATE INDEX "idempotency_keys_key_status_idx" ON "idempotency_keys"("key", "status");

-- CreateIndex
CREATE INDEX "idempotency_keys_expiresAt_idx" ON "idempotency_keys"("expiresAt");

-- CreateIndex
CREATE UNIQUE INDEX "oauth_token_cache_provider_key" ON "oauth_token_cache"("provider");

-- CreateIndex
CREATE INDEX "oauth_token_cache_provider_expiresAt_idx" ON "oauth_token_cache"("provider", "expiresAt");

-- CreateIndex
CREATE UNIQUE INDEX "orange_public_key_cache_keyId_key" ON "orange_public_key_cache"("keyId");

-- CreateIndex
CREATE INDEX "orange_public_key_cache_expiresAt_idx" ON "orange_public_key_cache"("expiresAt");

-- CreateIndex
CREATE UNIQUE INDEX "queue_jobs_jobId_key" ON "queue_jobs"("jobId");

-- CreateIndex
CREATE INDEX "queue_jobs_queueName_status_idx" ON "queue_jobs"("queueName", "status");

-- CreateIndex
CREATE INDEX "queue_jobs_transactionId_idx" ON "queue_jobs"("transactionId");

-- CreateIndex
CREATE INDEX "treasury_ledger_transactionId_idx" ON "treasury_ledger"("transactionId");

-- CreateIndex
CREATE INDEX "treasury_ledger_debitAccount_idx" ON "treasury_ledger"("debitAccount");

-- CreateIndex
CREATE INDEX "treasury_ledger_creditAccount_idx" ON "treasury_ledger"("creditAccount");

-- CreateIndex
CREATE INDEX "treasury_ledger_entryType_createdAt_idx" ON "treasury_ledger"("entryType", "createdAt");

-- CreateIndex
CREATE INDEX "treasury_ledger_status_createdAt_idx" ON "treasury_ledger"("status", "createdAt");

-- CreateIndex
CREATE INDEX "treasury_ledger_txHash_idx" ON "treasury_ledger"("txHash");

-- CreateIndex
CREATE INDEX "exchange_rates_fromCurrency_toCurrency_createdAt_idx" ON "exchange_rates"("fromCurrency", "toCurrency", "createdAt");

-- CreateIndex
CREATE UNIQUE INDEX "exchange_rates_fromCurrency_toCurrency_source_key" ON "exchange_rates"("fromCurrency", "toCurrency", "source");

-- CreateIndex
CREATE INDEX "audit_logs_userId_createdAt_idx" ON "audit_logs"("userId", "createdAt");

-- CreateIndex
CREATE INDEX "audit_logs_entityType_entityId_idx" ON "audit_logs"("entityType", "entityId");

-- CreateIndex
CREATE INDEX "agent_audit_logs_missionId_createdAt_idx" ON "agent_audit_logs"("missionId", "createdAt");

-- CreateIndex
CREATE INDEX "agent_audit_logs_node_createdAt_idx" ON "agent_audit_logs"("node", "createdAt");

-- CreateIndex
CREATE INDEX "agent_audit_logs_action_createdAt_idx" ON "agent_audit_logs"("action", "createdAt");

-- CreateIndex
CREATE UNIQUE INDEX "commission_records_transactionId_key" ON "commission_records"("transactionId");

-- CreateIndex
CREATE INDEX "commission_records_userId_idx" ON "commission_records"("userId");

-- CreateIndex
CREATE INDEX "commission_records_type_idx" ON "commission_records"("type");

-- CreateIndex
CREATE INDEX "commission_records_createdAt_idx" ON "commission_records"("createdAt");

-- CreateIndex
CREATE INDEX "morpho_transactions_userId_idx" ON "morpho_transactions"("userId");

-- CreateIndex
CREATE INDEX "morpho_transactions_type_idx" ON "morpho_transactions"("type");

-- CreateIndex
CREATE INDEX "morpho_transactions_status_idx" ON "morpho_transactions"("status");

-- CreateIndex
CREATE INDEX "morpho_transactions_marketId_idx" ON "morpho_transactions"("marketId");

-- CreateIndex
CREATE INDEX "morpho_transactions_vaultAddress_idx" ON "morpho_transactions"("vaultAddress");

-- CreateIndex
CREATE INDEX "morpho_transactions_createdAt_idx" ON "morpho_transactions"("createdAt");

-- CreateIndex
CREATE INDEX "morpho_market_positions_userId_idx" ON "morpho_market_positions"("userId");

-- CreateIndex
CREATE INDEX "morpho_market_positions_marketId_idx" ON "morpho_market_positions"("marketId");

-- CreateIndex
CREATE INDEX "morpho_market_positions_userAddress_idx" ON "morpho_market_positions"("userAddress");

-- CreateIndex
CREATE UNIQUE INDEX "morpho_market_positions_userId_marketId_key" ON "morpho_market_positions"("userId", "marketId");

-- CreateIndex
CREATE INDEX "morpho_vault_positions_userId_idx" ON "morpho_vault_positions"("userId");

-- CreateIndex
CREATE INDEX "morpho_vault_positions_vaultAddress_idx" ON "morpho_vault_positions"("vaultAddress");

-- CreateIndex
CREATE INDEX "morpho_vault_positions_userAddress_idx" ON "morpho_vault_positions"("userAddress");

-- CreateIndex
CREATE UNIQUE INDEX "morpho_vault_positions_userId_vaultAddress_key" ON "morpho_vault_positions"("userId", "vaultAddress");

-- CreateIndex
CREATE INDEX "morpho_markets_loanToken_idx" ON "morpho_markets"("loanToken");

-- CreateIndex
CREATE INDEX "morpho_markets_collateralToken_idx" ON "morpho_markets"("collateralToken");

-- CreateIndex
CREATE INDEX "morpho_markets_lastUpdate_idx" ON "morpho_markets"("lastUpdate");

-- CreateIndex
CREATE UNIQUE INDEX "morpho_vaults_address_key" ON "morpho_vaults"("address");

-- CreateIndex
CREATE INDEX "morpho_vaults_asset_idx" ON "morpho_vaults"("asset");

-- CreateIndex
CREATE INDEX "morpho_vaults_apy_idx" ON "morpho_vaults"("apy");

-- CreateIndex
CREATE INDEX "morpho_vaults_lastUpdate_idx" ON "morpho_vaults"("lastUpdate");

-- CreateIndex
CREATE UNIQUE INDEX "defi_bundled_operations_userOpHash_key" ON "defi_bundled_operations"("userOpHash");

-- CreateIndex
CREATE INDEX "defi_bundled_operations_walletId_idx" ON "defi_bundled_operations"("walletId");

-- CreateIndex
CREATE INDEX "defi_bundled_operations_protocol_idx" ON "defi_bundled_operations"("protocol");

-- CreateIndex
CREATE INDEX "defi_bundled_operations_status_idx" ON "defi_bundled_operations"("status");

-- CreateIndex
CREATE INDEX "defi_bundled_operations_chainId_idx" ON "defi_bundled_operations"("chainId");

-- CreateIndex
CREATE INDEX "defi_bundled_operations_createdAt_idx" ON "defi_bundled_operations"("createdAt");

-- CreateIndex
CREATE UNIQUE INDEX "defi_protocol_integrations_protocol_key" ON "defi_protocol_integrations"("protocol");

-- CreateIndex
CREATE INDEX "defi_protocol_integrations_protocol_idx" ON "defi_protocol_integrations"("protocol");

-- CreateIndex
CREATE INDEX "defi_protocol_integrations_chainId_idx" ON "defi_protocol_integrations"("chainId");

-- CreateIndex
CREATE INDEX "defi_protocol_integrations_isActive_idx" ON "defi_protocol_integrations"("isActive");

-- CreateIndex
CREATE UNIQUE INDEX "defi_protocol_integrations_protocol_chainId_key" ON "defi_protocol_integrations"("protocol", "chainId");

-- CreateIndex
CREATE INDEX "agent_missions_userId_status_idx" ON "agent_missions"("userId", "status");

-- CreateIndex
CREATE INDEX "agent_missions_endsAt_status_idx" ON "agent_missions"("endsAt", "status");

-- CreateIndex
CREATE INDEX "agent_missions_agentAddress_idx" ON "agent_missions"("agentAddress");

-- CreateIndex
CREATE INDEX "agent_missions_masterEoaAddress_idx" ON "agent_missions"("masterEoaAddress");

-- CreateIndex
CREATE UNIQUE INDEX "agent_signals_signalId_key" ON "agent_signals"("signalId");

-- CreateIndex
CREATE INDEX "agent_signals_generatedAt_idx" ON "agent_signals"("generatedAt");

-- CreateIndex
CREATE INDEX "agent_signals_asset_direction_idx" ON "agent_signals"("asset", "direction");

-- CreateIndex
CREATE INDEX "agent_signals_isProcessed_expiresAt_idx" ON "agent_signals"("isProcessed", "expiresAt");

-- CreateIndex
CREATE INDEX "agent_positions_missionId_status_idx" ON "agent_positions"("missionId", "status");

-- CreateIndex
CREATE INDEX "agent_positions_asset_status_idx" ON "agent_positions"("asset", "status");

-- CreateIndex
CREATE INDEX "agent_trade_executions_missionId_executedAt_idx" ON "agent_trade_executions"("missionId", "executedAt");

-- CreateIndex
CREATE INDEX "agent_trade_executions_signalId_idx" ON "agent_trade_executions"("signalId");

-- CreateIndex
CREATE INDEX "agent_pnl_snapshots_missionId_timestamp_idx" ON "agent_pnl_snapshots"("missionId", "timestamp");

-- CreateIndex
CREATE UNIQUE INDEX "platform_fee_records_missionId_key" ON "platform_fee_records"("missionId");

-- CreateIndex
CREATE INDEX "platform_fee_records_userId_idx" ON "platform_fee_records"("userId");

-- CreateIndex
CREATE INDEX "platform_fee_records_status_idx" ON "platform_fee_records"("status");

-- CreateIndex
CREATE INDEX "_GuardianVotes_B_index" ON "_GuardianVotes"("B");

-- AddForeignKey
ALTER TABLE "otp_codes" ADD CONSTRAINT "otp_codes_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "user_addresses" ADD CONSTRAINT "user_addresses_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "wallets" ADD CONSTRAINT "wallets_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "balances" ADD CONSTRAINT "balances_walletId_fkey" FOREIGN KEY ("walletId") REFERENCES "wallets"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "transactions" ADD CONSTRAINT "transactions_walletId_fkey" FOREIGN KEY ("walletId") REFERENCES "wallets"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "cross_chain_transactions" ADD CONSTRAINT "cross_chain_transactions_sourceWalletId_fkey" FOREIGN KEY ("sourceWalletId") REFERENCES "wallets"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "wallet_activity" ADD CONSTRAINT "wallet_activity_walletId_fkey" FOREIGN KEY ("walletId") REFERENCES "wallets"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "wallet_activity" ADD CONSTRAINT "wallet_activity_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "gas_analytics" ADD CONSTRAINT "gas_analytics_walletId_fkey" FOREIGN KEY ("walletId") REFERENCES "wallets"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "session_keys" ADD CONSTRAINT "session_keys_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "session_keys" ADD CONSTRAINT "session_keys_walletId_fkey" FOREIGN KEY ("walletId") REFERENCES "wallets"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "turnkey_signers" ADD CONSTRAINT "turnkey_signers_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "turnkey_signers" ADD CONSTRAINT "turnkey_signers_walletId_fkey" FOREIGN KEY ("walletId") REFERENCES "wallets"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "kernel_accounts" ADD CONSTRAINT "kernel_accounts_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "kernel_accounts" ADD CONSTRAINT "kernel_accounts_walletId_fkey" FOREIGN KEY ("walletId") REFERENCES "wallets"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "user_operations" ADD CONSTRAINT "user_operations_walletId_fkey" FOREIGN KEY ("walletId") REFERENCES "wallets"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notification_settings" ADD CONSTRAINT "notification_settings_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "devices" ADD CONSTRAINT "devices_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "passkey_credentials" ADD CONSTRAINT "passkey_credentials_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "passkey_sessions" ADD CONSTRAINT "passkey_sessions_passkeyCredentialId_fkey" FOREIGN KEY ("passkeyCredentialId") REFERENCES "passkey_credentials"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "social_recovery_guardians" ADD CONSTRAINT "social_recovery_guardians_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "recovery_sessions" ADD CONSTRAINT "recovery_sessions_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "recovery_sessions" ADD CONSTRAINT "recovery_sessions_initiatedByGuardianId_fkey" FOREIGN KEY ("initiatedByGuardianId") REFERENCES "social_recovery_guardians"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "passkey_security_events" ADD CONSTRAINT "passkey_security_events_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "auth_challenges" ADD CONSTRAINT "auth_challenges_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "webauthn_challenges" ADD CONSTRAINT "webauthn_challenges_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "momo_transactions" ADD CONSTRAINT "momo_transactions_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "momo_transactions" ADD CONSTRAINT "momo_transactions_providerId_fkey" FOREIGN KEY ("providerId") REFERENCES "momo_providers"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "transaction_fees" ADD CONSTRAINT "transaction_fees_transactionId_fkey" FOREIGN KEY ("transactionId") REFERENCES "momo_transactions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "transaction_fees" ADD CONSTRAINT "transaction_fees_providerId_fkey" FOREIGN KEY ("providerId") REFERENCES "momo_providers"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "wallet_momo_mappings" ADD CONSTRAINT "wallet_momo_mappings_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "wallet_momo_mappings" ADD CONSTRAINT "wallet_momo_mappings_providerId_fkey" FOREIGN KEY ("providerId") REFERENCES "momo_providers"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "transaction_limits" ADD CONSTRAINT "transaction_limits_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "webhook_deliveries" ADD CONSTRAINT "webhook_deliveries_transactionId_fkey" FOREIGN KEY ("transactionId") REFERENCES "momo_transactions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "transaction_state_history" ADD CONSTRAINT "transaction_state_history_transactionId_fkey" FOREIGN KEY ("transactionId") REFERENCES "momo_transactions"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "commission_records" ADD CONSTRAINT "commission_records_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "morpho_transactions" ADD CONSTRAINT "morpho_transactions_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "morpho_market_positions" ADD CONSTRAINT "morpho_market_positions_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "morpho_vault_positions" ADD CONSTRAINT "morpho_vault_positions_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "defi_bundled_operations" ADD CONSTRAINT "defi_bundled_operations_walletId_fkey" FOREIGN KEY ("walletId") REFERENCES "wallets"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "agent_missions" ADD CONSTRAINT "agent_missions_turnkeySignerId_fkey" FOREIGN KEY ("turnkeySignerId") REFERENCES "turnkey_signers"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "agent_positions" ADD CONSTRAINT "agent_positions_missionId_fkey" FOREIGN KEY ("missionId") REFERENCES "agent_missions"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "agent_trade_executions" ADD CONSTRAINT "agent_trade_executions_missionId_fkey" FOREIGN KEY ("missionId") REFERENCES "agent_missions"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "agent_pnl_snapshots" ADD CONSTRAINT "agent_pnl_snapshots_missionId_fkey" FOREIGN KEY ("missionId") REFERENCES "agent_missions"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_GuardianVotes" ADD CONSTRAINT "_GuardianVotes_A_fkey" FOREIGN KEY ("A") REFERENCES "recovery_sessions"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_GuardianVotes" ADD CONSTRAINT "_GuardianVotes_B_fkey" FOREIGN KEY ("B") REFERENCES "social_recovery_guardians"("id") ON DELETE CASCADE ON UPDATE CASCADE;

